spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MYSQL

  profiles:
    active: local

server:
  port: 8081
  servlet:
    context-path: /event-engine

logging:
  level:
    org.hibernate: ERROR
    org.springframework: INFO
    con.cnl.eventengine: DEBUG
    org.apache.kafka: ERROR

#app:
#  security:
#    jwtSecret: JWTSuperSecretKey
#    jwtExpirationInMs: 604800000

adapter:
  spring:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: event-engine
        topic: Collection_Event
      producer:
        bootstrap-servers: localhost:9092
        topic: Occurrence_Event

management:
  endpoints:
    web:
      exposure:
        include: '*'

--- #test 환경
spring:
  profiles: test
  h2:
    console:
      enabled: true

--- #local 환경
spring:
  profiles: local
  logging:
    root: debug
    level:

--- #dev
spring:
  profiles: dev
  logging:
    level:
      root: info